### PR TITLE
Dockerize `beautiful_atoms` environment and CI/CD

### PR DESCRIPTION
**Pull request by alchem0x2A**
PR to #2 
This is WIP PR to wrap-up the `beautiful_atoms` package into a single Docker image. CI/CD for building the image and testing `batoms` are also added as Github Actions. Note the tests in this PR won't directly work without additional modifications on the CI/CD settings and blender version matching, so we should discuss the maintanance before merging @superstar54 

# Brief description of the changes

1. Move all addon-related codes to `batoms/` folder. The files are branched from v2.0.0 pre-release but can merge any further versions
2. Dockerfiles are created under `Dockerfiles/Dockerfile.*`
3. Unit tests folder remain untouched

## About the docker image:

Currently built and pushed to my dockerhub with following names:
- `luciusm/beautiful_atoms:blender2.93`
- `luciusm/beautiful_atoms:blender3.0`
    With 2.93 and 3.0 version blender + v2.0.0 prerelease addon code. Native python in blender is replaced with conda ones, and `pymatgen` + `ase` stacks installed.
    The proposed usage would be:
    ```
    docker run --rm -v <local_path>:/workdir luciusm/beautiful_atoms:blender3.0 blender -b -P <path_to_script.py>
    ```
    where the `docker run` prefix can be potentially configured via environment variable in `batoms_api` (*TODO*)

    Bringing up Blender GUI should be feasible via X-forwarding. 

## CI/CD

Currently added 3 workflows:
1. Build blender environment images (2.93 & 3.0), for testing and pre-layer of the main image
2. Lint and unittest the addon before adding to main image.
3. Build main `beautiful_atoms` image. Currently on the v2.0.0 tree. (*Do we need backward compatibility?*)

## What's not working (yet)
1. Currently no way to ensure backward compatibility to v1.x.
2. Lint for batoms code fails
3. Simple geometry generation fails in blender 3.0, returning error `RuntimeError: internal error setting the array`

## Proposed steps before merging
1. env image and CI/CD can be merged first to dev / main branch
2. building of main image wait until dev CI/CD all clear (both blender versions)
3. consider merge `batoms_api` functionality into this repo (as the current folder structure allows)

### CODE REVIEW

**Comment by alchem0x2A** [comment]
- universal installation script (`install.sh`) --> `curl github.com/superstar45/xx/install.sh | bash`
- action test of install.sh
- merge`batom_api`
- `batoms_api` pypi actions

User case?

**Comment by alchem0x2A** [comment]
- universal installation script (`install.sh`) --> `curl github.com/superstar45/xx/install.sh | bash`
- action test of install.sh
- merge`batom_api`
- `batoms_api` pypi actions

User case?

**Comment by alchem0x2A** [comment]
@superstar54  For installation scripts the COMPAS project has full supported script to merge conda environment with Blender https://github.com/compas-dev/compas Maybe worth porting codes from there for the installation script. I'll give a try

**Comment by superstar54** [comment]
@alchem0x2A The ``RuntimeError: internal error setting the array`` could be related to the old input file from v1. I have updated the document to 2.0 (https://beautiful-atoms.readthedocs.io/en/latest/index.html). Please use the examples there.

Branch ``release/2.0.0`` now supports both Blender 3.0 and 3.1. Please test it again using this branch.

**Pull request merged**
